"""ARA report command — generate Markdown/HTML reports for GitHub repos.

Usage:
    ara report facebook/react --format md       # Markdown report
    ara report facebook/react --format md --output REPORT.md
    ara report lijiajing-11/alpha-project-arena --format html
"""

from __future__ import annotations

import json
import shutil
import textwrap
from datetime import datetime, timezone

from .colors import BOLD, CYAN, GREEN, GRAY, GOLD, RED, RESET, YELLOW
from .core import GitHubClient
from .insight import (
    _build_insight_data,
    compute_influence_score,
    compute_star_velocity,
    compute_repo_age,
)  

REPORT_WIDTH = 72


# ---------------------------------------------------------------------------
# Data collector — gathers everything ARA knows about a repo
# ---------------------------------------------------------------------------


def _collect_report_data(repo: str, client: GitHubClient) -> dict:
    """Gather all available data fields for a single repo into one dict.

    Combines insight data for a single source of truth.
    """
    insight = _build_insight_data(repo, client)

    data = {
        **insight,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "generated_by": "ARA CLI (github-stars-cli)",
    }

    # Ensure influence score
    if "influence_score" not in data:
        data["influence_score"] = compute_influence_score(data)

    return data


# ---------------------------------------------------------------------------
# Markdown renderer
# ---------------------------------------------------------------------------


def _md_report(data: dict) -> str:
    """Render a full Markdown report for one repo."""
    name = data.get("full_name", "unknown/repo")
    desc = data.get("description", "No description")
    stars = data.get("stars", 0)
    forks = data.get("forks", 0)
    open_issues = data.get("open_issues", 0)
    lang = data.get("language", "N/A")
    license_name = data.get("license", "N/A")
    topics = data.get("topics", [])
    created = data.get("created_at", "")
    updated = data.get("updated_at", "")
    spd, vel_label = compute_star_velocity(stars, created)
    age_years, age_label = compute_repo_age(created)
    influence = data.get("influence_score", 0)

    lines = []
    _w = lines.append

    _w(f"# 📊 {name}")
    _w("")
    _w(f"> {desc}")
    _w("")
    _w(f"| Metric | Value |")
    _w(f"|--------|-------|")
    _w(f"| ⭐ **Stars** | {stars:,} |")
    _w(f"| 🍴 **Forks** | {forks:,} |")
    _w(f"| 🐛 **Open Issues** | {open_issues:,} |")
    _w(f"| 🔤 **Language** | {lang} |")
    _w(f"| 📜 **License** | {license_name} |")
    _w(f"| 🏷️ **Topics** | {', '.join(topics[:8]) if topics else 'N/A'} |")
    _w(f"| 🚀 **Star Velocity** | {spd} / day ({vel_label}) |")
    _w(f"| 📅 **Created** | {created[:10] if created else 'N/A'} ({age_label}, {age_years:.1f} yr) |")
    _w(f"| 🔄 **Updated** | {updated[:10] if updated else 'N/A'} |")
    _w(f"| 🏆 **Influence Score** | {influence:.1f} |")
    _w("")

    # Influence score explanation
    _w("## 🏆 Influence Score Breakdown")
    _w("")
    _w(f"The **influence score** ({influence:.1f}) is a composite metric that weighs:")
    _w("")
    _w(f"- **Star power**: normalized star count")
    _w(f"- **Community engagement**: fork/issue activity")
    _w(f"- **Velocity**: growth rate over time")
    _w("")

    # Embeddable badge section
    _w("## 🛡️ Quick Status")
    _w("")
    vel_icon = "🚀" if "Hypersonic" in vel_label else ("🔥" if "Rapid" in vel_label else "🐢")
    age_icon = "🏛️" if "Veteran" in age_label else ("💪" if "Prime" in age_label else "🌱")
    _w(f"- {vel_icon} **Velocity**: {spd} stars/day — {vel_label}")
    _w(f"- {age_icon} **Maturity**: {age_years:.1f} years — {age_label}")
    _w(f"- ⭐ **Stars**: {stars:,}")
    _w(f"- 🍴 **Forks**: {forks:,}")
    _w("")

    # Footer
    _w("---")
    _w(f"_Generated by [ARA CLI](https://github.com/lijiajing-11/alpha-project-arena) on {data['generated_at'][:19]} UTC_")
    _w("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# HTML renderer (simple, embeddable)
# ---------------------------------------------------------------------------


def _html_report(data: dict) -> str:
    """Render a minimal HTML report snippet."""
    name = data.get("full_name", "unknown/repo")
    desc = data.get("description", "No description")
    stars = data.get("stars", 0)
    forks = data.get("forks", 0)
    spd, vel_label = compute_star_velocity(stars, data.get("created_at", ""))
    age_years, age_label = compute_repo_age(data.get("created_at", ""))
    influence = data.get("influence_score", 0)

    return textwrap.dedent(f"""\
    <div style="border:1px solid #ddd;border-radius:12px;padding:20px;max-width:600px;font-family:sans-serif">
      <h2>📊 {name}</h2>
      <p style="color:#666">{desc}</p>
      <table style="width:100%;border-collapse:collapse">
        <tr><td>⭐ Stars</td><td><strong>{stars:,}</strong></td><td>🚀 Velocity</td><td><strong>{spd}/day</strong></td></tr>
        <tr><td>🍴 Forks</td><td><strong>{forks:,}</strong></td><td>🏆 Influence</td><td><strong>{influence:.1f}</strong></td></tr>
        <tr><td>📅 Age</td><td><strong>{age_years:.1f} yr</strong></td><td>🏷️ Label</td><td><strong>{age_label}</strong></td></tr>
      </table>
      <p style="font-size:0.8em;color:#999;margin-top:12px">Generated by ARA CLI</p>
    </div>
    """)


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def cmd_report(args, client: GitHubClient) -> None:
    """Handle `ara report <repo> [--format md|html] [--output FILE]`."""
    repo = args.repo
    fmt = getattr(args, "format", "md") or "md"
    out_path = getattr(args, "output", None)

    data = _collect_report_data(repo, client)

    if fmt == "html":
        output = _html_report(data)
    else:
        output = _md_report(data)

    if out_path:
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(output)
        print(f"  ✅ Report saved → {out_path}")
    else:
        print(output)
